### ISSUE TITLE
getRawValue and getFormattedValue both fail on non-string columns

### ISSUE THREAD

**Issue by JonnyAdaptableTools** [jonathannaim/adaptablegrid#3]
Looks like as though its failing on a tostring() call when the column is not a string

**Comment by jasonlipo** [comment]
Odd. I can't seem to reproduce this error.
On my console, I can run:

mygrid.getRow(3).getCell(4).getRawValue()
\> 373.54014505239024

mygrid.getRow(3).getCell(4).getFormattedValue()
\> "373.54"

Maybe I'm missing something? What do you mean by a "toString()" call?

**Comment by JonnyAdaptableTools** [comment]
its my bug that is causing the error mainly.  which I've fixed.
but on numeric columns get.FormattedValue() is returning an integer not a string (even though that is what the method suggests)
e.g.  let test = cell.getFormattedValue(this.grid) 
where the value in the cell returns 1 and not "1".  
i can handle this so we can close this issue but just mentioning it as probably worth tidying up.
