### ISSUE TITLE
add a getallrowids() method

### ISSUE THREAD

**Issue by JonnyAdaptableTools** [jonathannaim/adaptablegrid#6]
Not so urgent this as we can loop through all the rows and call getrowidbyrow but i guess if you can do it - and make it super quick by using JQuery - then it might be helpful...

definitely not urgent.

**Comment by jasonlipo** [comment]
Not quite sure what you mean, something like doing this?

```javascript
var rowIds = [];
for (row in grid.getAllRows()) {
  rowIds.push(row.getId());
}
```

**Comment by JonnyAdaptableTools** [comment]
yeah, good point. its unnecessary.  I'll drop the idea altogether and close the jira.
