### ISSUE TITLE
Add concept of ReadOnly / editable

### ISSUE THREAD

**Issue by JonnyAdaptableTools** [jonathannaim/adaptablegrid#8]
So I think you need to allow a column to be Readonly.  this can then be set by the dev at design time when they set up the grid.  if its readonly then you cannot enter edit mode for the column.
And also the column object should have an IsReadOnly or IsEditable or some similar property to say if readonly has been set.
This is quite useful in lots of scenarios.

**Comment by jonathannaim** [comment]
If you work on that Jason you might want to include directly the fact that some records can be readonly and some not depending on some conditions. i.e. Trade Price can be edited for all trade status but is readonly when trade is validated.

I'm linking to the same issue on the adaptable blotter side : jonathannaim/adaptableblotter#15

**Comment by jasonlipo** [comment]
At design time, you can add `readonly: true` to the column definition, but once the grid is created, the read-only properties are applied to the individual Cells. So in the Cell object, you can call `isReadOnly()` or `setReadOnly` but there is no "readonly" property for the whole column. Is that something you want me to add? It must just be useful to add a method to the Column object to make all its cell either read-only or not...

**Comment by JonnyAdaptableTools** [comment]
I think the absolute minimum we need is an IsReadOnly property / method on a column.

so if its set to readonly at design time then at runtime I can see that.  its important for functions where we edit outside the grid (e.g. smart edit) and we want to disallow it at run time

**Comment by jasonlipo** [comment]
Ok, just a few questions about that then (sorry if this is completely my stupidity).
So a Column can have a "readonly" property and so can a Cell.
So if a Column is "readonly" and then one individual Cell in that column is set to editable, does the Column keep its "readonly" property?
And if you were to apply Column.setReadOnly() would it change that original Cell back to read-only?

**Comment by jonathannaim** [comment]
My view is that we should follow the following pattern ( @ponfus  do you agree?)
- a column at design time can be set as editable or non readonly or the opposite pattern readonly...
- at runtime we should check at the cell level according to the record and not at the column level

jonny, that's why I think we have the logic wrong in AB and I created the issue in our repo. We shouldnt check the readonly at the column level but for every record we want to edit.

**Comment by JonnyAdaptableTools** [comment]
yes, ok, that makes sense

jason - I dont think we need a column.setreadonly()
